let Data = [

  {
    id: 1,
    image: '../image/data/AlbanySectional.jpg',
    name: "Bar Stool",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 309,
    Available: true,
    Brand: "Godrej Interio",
    color: "black",
    quantity: 4,
    showcase: false,
    category: 'Dinning Table'
  }, {
    id: 2,
    image: '../image/data/AlbanyTable.jpg',
    name: "Albany Table",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 3099,
    Available: true,
    Brand: "Godrej Interio",
    color: "black",
    quantity: 6,
    showcase: false,
    category: 'Kitchen Table'
  },
  {
    id: 3,
    image: '../image/data/Armchair.jpg',
    name: "Armchair",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1250,
    Available: true,
    Brand: "Nilkamal",
    color: "black",
    quantity: 5,
    showcase: false,
    category: 'Bedroom'
  },
  {
    id: 4,
    image: '../image/data/SuedeArmchair.jpg',
    name: "Suede Armchair",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1599,
    Available: true,
    Brand: "Hulsta",
    color: "black",
    quantity: 7,
    showcase: true,
    category: 'Office',
  },
  {
    id: 5,
    image: '../image/data/LeatherChair.jpg',
    name: "Leather Chair",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 255,
    Available: true,
    Brand: "Hulsta",
    color: "black",
    quantity: 8,
    showcase: false,
    category: 'Bedroom'
  },
  {
    id: 6,
    image: '../image/data/EmperorBed.jpg',
    name: "Emperor Bed",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 139,
    Available: false,
    Brand: "Ikea",
    color: "black",
    quantity: 5,
    showcase: false,
    category: 'Bedroom'
  },
  {
    id: 7,
    image: '../image/data/AccentChair.jpg',
    name: "Accent Chair",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 259,
    Available: true,
    Brand: "Nilkamal",
    color: "black",
    quantity: 5,
    showcase: false,
    category: 'Office'
  },
  {
    id: 8,
    image: '../image/data/Shelf.jpg',
    name: "Shelf",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 309,
    Available: true,
    Brand: "Ikea",
    color: "black",
    quantity: 5,
    showcase: false,
    category: 'Living Room'
  },
  {
    id: 9,
    image: '../image/data/ModernBookshelf.jpg  ',
    name: "Modern Bookshelf",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "319",
    Available: true,
    Brand: "Hulsta",
    color: "black",
    quantity: 8,
    showcase: false,
    category: 'Kids'
  },

  {
    id: 10,
    image: '../image/data/Wooden Desk1.jpg',
    name: "Wooden Desk",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1509,
    Available: true,
    Brand: "Ikea",
    color: "black",
    quantity: 6,
    showcase: false,
    category: 'Office'
  },
  {
    id: 11,
    image: '../image/data/Wooden Table.jpg',
    name: "Wooden Table",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 2349,
    Available: true,
    Brand: "Hulsta",
    color: "black",
    quantity: 10,
    showcase: false,
    category: 'Kitchen Table'
  },
  {
    id: 12,
    image: '../image/data/WoodenBed.jpg',
    name: "Wooden Bed",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 2100,
    Available: true,
    Brand: "Ikea",
    color: "black",
    quantity: 7,
    showcase: false,
    category: 'Bedroom'
  },
  {
    id: 13,
    image: '../image/data/AlbanyTable.jpg',
    name: "Albany Table",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 3099,
    Available: false,
    Brand: "Godrej Interio",
    color: "black",
    quantity: 5,
    showcase: false,
    category: 'Living Room'
  },
  {
    id: 14,
    image: '../image/data/High-BackBench.jpg',
    name: "High-Back Bench",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 399,
    Available: true,
    Brand: "Ikea",
    color: "black",
    quantity: 10,
    showcase: false,
    category: 'Office',
  },

  {
    id: 15,
    image: '../image/data/Wooden Desk2.jpg',
    name: "Wooden Desk",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1752,
    Available: false,
    Brand: "Ikea",
    color: "black",
    quantity: 5,
    showcase: true,
    category: 'Office',
  },

  {
    id: 16,
    image: '../image/data/DiningTable.jpg',
    name: "Dinning Table Table",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1299,
    Available: true,
    Brand: "Ikea",
    color: "black",
    quantity: 4,
    showcase: false,
    category: 'Dinning Table'
  },
  {
    id: 17,
    image: '../image/data/EntertainmentCenter.jpg',
    name: "Entertainment Center",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 3099,
    Available: true,
    Brand: "Ikea",
    color: "Hulsta",
    quantity: 6,
    showcase: false,
    category: 'Living Room'
  },
  {
    id: 18,
    image: '../image/data/UtopiaSofa.jpg',
    name: "Utopia Sofa",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1500,
    Available: true,
    Brand: "Godrej Interio",
    color: "black",
    quantity: 4,
    showcase: false,
    category: 'Living Room'
  },
  {
    id: 19,
    image: '../image/data/LeatherSofa.jpg',
    name: "Leather Sofa",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1750,
    Available: true,
    Brand: "Godrej Interio",
    color: "black",
    quantity: 6,
    showcase: false,
    category: 'Office'
  },
  {
    id: 20,
    image: '../image/data/AlbanySectional.jpg',
    name: "Albany Sectional",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1099,
    Available: false,
    Brand: "Godrej Interio",
    color: "black",
    quantity: 5,
    showcase: true,
    category: 'Living Room'
  },


  {
    id: 21,
    image: '../image/data/SimpleChair.jpg',
    name: "Simple Chair",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1200,
    Available: true,
    Brand: "Godrej Interio",
    color: "black",
    quantity: 4,
    showcase: false,
    category: 'Living Room'
  },
  {
    id: 22,
    image: '../image/data/Vase Table.jpg',
    name: "Vase Table",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1400,
    Available: true,
    Brand: "Nilkamal",
    color: "black",
    quantity: 6,
    showcase: false,
    category: 'Office',
  },
  {
    id: 23,
    image: '../image/data/SofaSet.jpg',
    name: "Sofa Set",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: 1500,
    Available: false,
    Brand: "Marcos",
    color: "black",
    quantity: 6,
    showcase: false,
    category: 'Living Room',
  },
];

export default Data;

