let Data = [
  {
    id: 1,
    image: './image/data/AlbanyTable.jpg',
    name: "Albany Table",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "3,099.99",
    Available: "in stock",
    Brand: "Godrej Interio",
    color: "black",
    quantity: 3,
    category: 'Kitchen Table'
  },
  {
    id: 2,
    image: './image/data/AlbanySectional.jpg',
    name: "Bar Stool",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "40.99",
    Available: "in stock",
    Brand: "Godrej Interio",
    color: "black",
    quantity: 10,
    category: 'Dinning Table'
  },
  {
    id: 3,
    image: './image/data/AlbanyTable.jpg',
    name: "Armchair",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "125.99",
    Available: "in Stock",
    Brand: "Nilkamal",
    color: "black",
    quantity: 5,
    category: 'Bedroom'
  },
  {
    id: 4,
    image: './image/data/Armchair.jpg',
    name: "Suede Armchair",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "159.99",
    Available: "in Stock",
    Brand: "Hulsta",
    color: "black",
    quantity: 3,
    category: 'Office'
  },
  {
    id: 5,
    image: './image/data/BarStool.jpg',
    name: "Leather Chair",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "200.99",
    Available: "in Stock",
    Brand: "Hulsta",
    color: "black",
    quantity: 3,
    category: 'Bedroom'
  },
  {
    id: 6,
    name: "Emperor Bed",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "239.99",
    Available: "Out Of Stock",
    Brand: "Ikea",
    color: "black",
    quantity: 3,
    category: 'Bedroom'
  },
  {
    id: 7,
    name: "Accent Chair",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "259.99",
    Available: "In Stock",
    Brand: "Nilkamal",
    color: "black",
    quantity: 3,
    category: 'Office'
  },
  {
    id: 8,
    name: "Shelf",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "309.99",
    Available: "In Stock",
    Brand: "Ikea",
    color: "black",
    quantity: 3,
    category: 'Living Room'
  },
  {
    id: 9,
    name: "Modern Bookshelf",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "319.99",
    Available: "In Stock",
    Brand: "Hulsta",
    color: "black",
    quantity: 3,
    category: 'Kids'
  },
  {
    id: 10,
    name: "High-Back Bench",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "399.99",
    Available: "In Stock",
    Brand: "Ikea",
    color: "black",
    quantity: 3,
    category: 'Office',
  },

  {
    id: 11,
    name: "Wooden Desk",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "400.99",
    Available: "In Stock",
    Brand: "Ikea",
    color: "black",
    quantity: 3,
    category: 'Office',
  },

  {
    id: 12,
    name: "Dinning Table Table",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "400.99",
    Available: "In Stock",
    Brand: "Ikea",
    color: "black",
    quantity: 3,
    category: 'Dinning Table'
  },
  {
    id: 13,
    name: "Entertainment Center",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "400.99",
    Available: "In Stock",
    Brand: "Ikea",
    color: "Hulsta",
    quantity: 3,
    category: 'Living Room'
  },
  {
    id: 14,
    name: "Utopia Sofa",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "799.99",
    Available: "In Stock",
    Brand: "Godrej Interio",
    color: "black",
    quantity: 3,
    category: 'Living Room'
  },
  {
    id: 15,
    name: "Leather Sofa",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "999.99",
    Available: "In Stock",
    Brand: "Godrej Interio",
    color: "black",
    quantity: 3,
    category: 'Office'
  },
  {
    id: 16,
    name: "Albany Sectional",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "1,099.99",
    Available: "out of Stock",
    Brand: "Godrej Interio",
    color: "black",
    quantity: 3,
    category: 'Living Room'
  },


  {
    id: 17,
    name: "Simple Chair",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "1,099.99",
    Available: "in Stock",
    Brand: "Godrej Interio",
    color: "black",
    quantity: 3,
    category: 'Living Room'
  },
  {
    id: 18,
    name: "Vase Table",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "1,209.99",
    Available: "in Stock",
    Brand: "Nilkamal",
    color: "black",
    quantity: 3,
    category: 'Office',
  },
  {
    id: 19,
    name: "Sofa Set",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "1,299.99",
    Available: "in Stock",
    Brand: "Marcos",
    color: "black",
    quantity: 3,
    category: 'Living Room',
  },
  {
    id: 20,
    name: "Wooden Desk",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "1,509.99",
    Available: "in Stock",
    Brand: "Ikea",
    color: "black",
    quantity: 3,
    category: 'Office'
  },
  {
    id: 21,
    name: "Wooden Table",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "2,349.99",
    Available: "in Stock",
    Brand: "Hulsta",
    color: "black",
    quantity: 3,
    category: 'Kitchen Table'
  },
  {
    id: 22,
    name: "Wooden Bed",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "2,349.99",
    Available: "in Stock",
    Brand: "Ikea",
    color: "black",
    quantity: 3,
    category: 'Bedroom'
  },
  {
    id: 23,
    name: "Albany Table",
    info: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    price: "3,099.99",
    Available: "in Stock",
    Brand: "Godrej Interio",
    color: "black",
    quantity: 3,
    category: 'Living Room'
  },
];

export default Data;

